In [1]:
# creating the new array
import numpy as np
print(np.array([1,2,3]))

[1 2 3]


In [2]:
print("hello")

hello


In [3]:
import numpy as np
arr = np.array([10,20,30,40,50])
print(arr)

[10 20 30 40 50]


In [4]:
# check version
print(np.__version__)

1.26.4


In [5]:
# Check array type
arr2 = np.array([1,2,3,4,5])
print(type(arr2))

<class 'numpy.ndarray'>


In [6]:
# 0 dimension array
import numpy as np
arr = np.array(24)
print(arr)

24


In [7]:
# 1 dimension array
import numpy as np
arr1 = np.array([1,2,3])
print(arr1)

[1 2 3]


In [8]:
# 2 dimension array
import numpy as np
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [9]:
# 2 dimension array
import numpy as np
arr3 = np.array([[[1,2,3],[4,5,6],[7,8,9],[7,8,9]]])
print(arr3)

[[[1 2 3]
  [4 5 6]
  [7 8 9]
  [7 8 9]]]


In [10]:
print(arr3.ndim)

3


In [11]:
# 3 dimension array
import numpy as np
arr4 = np.array([[[1,2,3,4],[4,5,6,5]],[[7,8,9,5],[10,11,12,4]]])
print(arr4)

[[[ 1  2  3  4]
  [ 4  5  6  5]]

 [[ 7  8  9  5]
  [10 11 12  4]]]


In [12]:
print(arr4.ndim)

3


In [13]:
# elements accessing in np - 1D array
arr = np.array([1,2,3,4,5])
print(arr[2])


3


In [14]:
# elements accessing in 2D array
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print (arr[0,4])

5


In [15]:
# negative indesing in 1D array - accessing elements from right to left
arr = np.array([1,2,3,4,5])
print(arr[-2])

4


In [16]:
# negative indesing in 2D array - accessing elements from right to left
import numpy as np
arr = np.array([[1,2,3,4,5],
              [6,7,8,9,10]])
print(arr[1,-2])

9


In [17]:
# slicing elements from array
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr[0:11:2])

[1 3 5 7 9]


In [18]:
# slicing with negative indexing 
arr = np.array([1,2,3,4,5,6])
print(arr[-5:-2])

[2 3 4]


In [19]:
# check datatype of an array
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr.dtype)

int32


In [20]:
# Conversion of datatype
print(arr.astype(float))

[1. 2. 3. 4. 5.]


In [21]:
# check shape of an array
import numpy as np
arr = np.array([1,2,3,4,5,62,3,4,5,5,6])
print(arr.shape)

(11,)


In [22]:
# check size of an array
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr.size)

5


In [23]:
# reshape if an array
import numpy as np
arr = np.array([2,3,4,5,6,7,8,4,5,6,7,8])
newarr = arr.reshape(3,4)
print(newarr)

[[2 3 4 5]
 [6 7 8 4]
 [5 6 7 8]]


In [24]:
# Iterating array elements
arr = np.array([1,2,3,4,5])
for x in arr:
    print(x)

1
2
3
4
5


In [25]:
# Joining array
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])
arr = np.concatenate([arr1,arr2])
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [26]:
# Splitting of an array
arr = np.array([1,2,3,4,5,6,7])
newarr = np.array_split(arr,2)
print(newarr)

[array([1, 2, 3, 4]), array([5, 6, 7])]


In [27]:
# Searching of an array
arr = np.array([1,2,3,4,5,6])
arr1 = np.array([1.3,2.4,3.5,4.4,5.5,6.6])
x = np.where(arr1 == 1.3)
print(x)

(array([0], dtype=int64),)


In [28]:
# Sorting of array
    # Ascending order
arr = np.array([1,3,4,0])
print("ascending order", np.sort(arr))

    # Descending order
arr1 = np.array([1,3,4,0])
print("descending order",np.sort(arr1)[::-1])

ascending order [0 1 3 4]
descending order [4 3 1 0]


In [29]:
# Filtering of array elements
arr = np.array([41,42,43,44])
x = True,False,True,False
newarr = arr
print(newarr)

[41 42 43 44]


In [34]:
arr = np.array([41,42,43,44])
    #create an empty list
filter_arr = []
    # go through each element in arr
for element in arr:
    # if the elements are higher than 42 set the value to true otherwise false
    if element > 42:
        filter_arr.append(True)
    else:
        filter_arr.append(False)
newarr = arr[filter_arr]
print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]


In [ ]:
    # Adding and removing elements
import numpy as np
arr = np.array([10,20,30,40,50])
    # append (adds at last)
arr = np.array([10,20,30,40,50])
print(np.append(arr,[60,70]))

    # Insert (adds in specific index)
print(np.insert(arr,4,80))

    # Deleting of an element by its index
print (np.delete(arr,[3]))

In [ ]:
# Aggregate functions 
a = np.array([10,20,30,40,50])
    #sum
print(np.sum(a))
    #minimum
print(np.min(a))
    #maximum
print(np.max(a))
    #cimulative sum
print(np.cumsum(a))