In [7]:
import numpy as np
import pandas as pd

In [8]:
# Import dataset
ds = pd.read_csv("data_1.csv")
ds

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [9]:
# import ml library
!pip install scikit-learn

In [10]:
# handling missing value using meann and scikit learn


from sklearn.impute import SimpleImputer
import numpy as np

si = SimpleImputer(missing_values=np.nan, strategy='mean')
ds[["Age", "Salary"]] = si.fit_transform(ds[["Age", "Salary"]])


In [11]:
ds

Country        Age        Salary Purchased
0   France  44.000000  72000.000000        No
1    Spain  27.000000  48000.000000       Yes
2  Germany  30.000000  54000.000000        No
3    Spain  38.000000  61000.000000        No
4  Germany  40.000000  63777.777778       Yes
5   France  35.000000  58000.000000       Yes
6    Spain  38.777778  52000.000000        No
7   France  48.000000  79000.000000       Yes
8  Germany  50.000000  83000.000000        No
9   France  37.000000  67000.000000       Yes

In [12]:
# encoding categical column (one hot encoder)

from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder(sparse_output=False) 
encoded_data = ohe.fit_transform(ds[['Country']])
print(encoded_data)


[[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]]


In [13]:
# make column headers and make a dataframe for array

column_names = ohe.get_feature_names_out(['Country'])
encoded_df = pd.DataFrame(encoded_data, columns = column_names)
encoded_df

Country_France  Country_Germany  Country_Spain
0             1.0              0.0            0.0
1             0.0              0.0            1.0
2             0.0              1.0            0.0
3             0.0              0.0            1.0
4             0.0              1.0            0.0
5             1.0              0.0            0.0
6             0.0              0.0            1.0
7             1.0              0.0            0.0
8             0.0              1.0            0.0
9             1.0              0.0            0.0

In [14]:
# Joining original and new dataset

ds = pd.concat([ds,encoded_df], axis = 1)
ds

Country        Age        Salary Purchased  Country_France  \
0   France  44.000000  72000.000000        No             1.0   
1    Spain  27.000000  48000.000000       Yes             0.0   
2  Germany  30.000000  54000.000000        No             0.0   
3    Spain  38.000000  61000.000000        No             0.0   
4  Germany  40.000000  63777.777778       Yes             0.0   
5   France  35.000000  58000.000000       Yes             1.0   
6    Spain  38.777778  52000.000000        No             0.0   
7   France  48.000000  79000.000000       Yes             1.0   
8  Germany  50.000000  83000.000000        No             0.0   
9   France  37.000000  67000.000000       Yes             1.0   

   Country_Germany  Country_Spain  
0              0.0            0.0  
1              0.0            1.0  
2              1.0            0.0  
3              0.0            1.0  
4              1.0            0.0  
5              0.0            0.0  
6              0.0            1.0  
7              0.0            0.0  
8              1.0            0.0  
9              0.0            0.0

In [17]:
ds = ds.loc[:, ~ds.columns.duplicated()]
ds

Country        Age        Salary Purchased  Country_France  \
0   France  44.000000  72000.000000        No             1.0   
1    Spain  27.000000  48000.000000       Yes             0.0   
2  Germany  30.000000  54000.000000        No             0.0   
3    Spain  38.000000  61000.000000        No             0.0   
4  Germany  40.000000  63777.777778       Yes             0.0   
5   France  35.000000  58000.000000       Yes             1.0   
6    Spain  38.777778  52000.000000        No             0.0   
7   France  48.000000  79000.000000       Yes             1.0   
8  Germany  50.000000  83000.000000        No             0.0   
9   France  37.000000  67000.000000       Yes             1.0   

   Country_Germany  Country_Spain  
0              0.0            0.0  
1              0.0            1.0  
2              1.0            0.0  
3              0.0            1.0  
4              1.0            0.0  
5              0.0            0.0  
6              0.0            1.0  
7              0.0            0.0  
8              1.0            0.0  
9              0.0            0.0

In [18]:
# droping categarical column

ds = ds.drop(['Country'], axis = 1)
ds

Age        Salary Purchased  Country_France  Country_Germany  \
0  44.000000  72000.000000        No             1.0              0.0   
1  27.000000  48000.000000       Yes             0.0              0.0   
2  30.000000  54000.000000        No             0.0              1.0   
3  38.000000  61000.000000        No             0.0              0.0   
4  40.000000  63777.777778       Yes             0.0              1.0   
5  35.000000  58000.000000       Yes             1.0              0.0   
6  38.777778  52000.000000        No             0.0              0.0   
7  48.000000  79000.000000       Yes             1.0              0.0   
8  50.000000  83000.000000        No             0.0              1.0   
9  37.000000  67000.000000       Yes             1.0              0.0   

   Country_Spain  
0            0.0  
1            1.0  
2            0.0  
3            1.0  
4            0.0  
5            0.0  
6            1.0  
7            0.0  
8            0.0  
9            0.0

In [16]:
# Label encoding

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
ds['Purchased'] = le.fit_transform(ds['Purchased'])

In [17]:
ds

Country        Age        Salary  Purchased  Country_France  \
0   France  44.000000  72000.000000          0             1.0   
1    Spain  27.000000  48000.000000          1             0.0   
2  Germany  30.000000  54000.000000          0             0.0   
3    Spain  38.000000  61000.000000          0             0.0   
4  Germany  40.000000  63777.777778          1             0.0   
5   France  35.000000  58000.000000          1             1.0   
6    Spain  38.777778  52000.000000          0             0.0   
7   France  48.000000  79000.000000          1             1.0   
8  Germany  50.000000  83000.000000          0             0.0   
9   France  37.000000  67000.000000          1             1.0   

   Country_Germany  Country_Spain  
0              0.0            0.0  
1              0.0            1.0  
2              1.0            0.0  
3              0.0            1.0  
4              1.0            0.0  
5              0.0            0.0  
6              0.0            1.0  
7              0.0            0.0  
8              1.0            0.0  
9              0.0            0.0

In [22]:
# Feature scaling(Reduce laarger data values to its smller data values)

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
ds[['Age','Salary']] = sc.fit_transform(ds[['Age','Salary']])

In [21]:
ds

Age        Salary  Purchased  Country_France  Country_Germany  \
0  0.758874  7.494733e-01          0             1.0              0.0   
1 -1.711504 -1.438178e+00          1             0.0              0.0   
2 -1.275555 -8.912655e-01          0             0.0              1.0   
3 -0.113024 -2.532004e-01          0             0.0              0.0   
4  0.177609  6.632192e-16          1             0.0              1.0   
5 -0.548973 -5.266569e-01          1             1.0              0.0   
6  0.000000 -1.073570e+00          0             0.0              0.0   
7  1.340140  1.387538e+00          1             1.0              0.0   
8  1.630773  1.752147e+00          0             0.0              1.0   
9 -0.258340  2.937125e-01          1             1.0              0.0   

   Country_Spain  
0            0.0  
1            1.0  
2            0.0  
3            1.0  
4            0.0  
5            0.0  
6            1.0  
7            0.0  
8            0.0  
9            0.0

In [20]:
# Divide dataset as independent (input) and dependaent (output) variables

x = ds[['Age','Salary','Country_France','Country_Germany','Country_Spain']]
y = ds[['Purchased']]

In [21]:
ds

Country        Age        Salary  Purchased  Country_France  \
0   France  44.000000  72000.000000          0             1.0   
1    Spain  27.000000  48000.000000          1             0.0   
2  Germany  30.000000  54000.000000          0             0.0   
3    Spain  38.000000  61000.000000          0             0.0   
4  Germany  40.000000  63777.777778          1             0.0   
5   France  35.000000  58000.000000          1             1.0   
6    Spain  38.777778  52000.000000          0             0.0   
7   France  48.000000  79000.000000          1             1.0   
8  Germany  50.000000  83000.000000          0             0.0   
9   France  37.000000  67000.000000          1             1.0   

   Country_Germany  Country_Spain  
0              0.0            0.0  
1              0.0            1.0  
2              1.0            0.0  
3              0.0            1.0  
4              1.0            0.0  
5              0.0            0.0  
6              0.0            1.0  
7              0.0            0.0  
8              1.0            0.0  
9              0.0            0.0

In [22]:
y

Purchased
0          0
1          1
2          0
3          0
4          1
5          1
6          0
7          1
8          0
9          1

In [23]:
x

Age        Salary  Country_France  Country_Germany  Country_Spain
0  44.000000  72000.000000             1.0              0.0            0.0
1  27.000000  48000.000000             0.0              0.0            1.0
2  30.000000  54000.000000             0.0              1.0            0.0
3  38.000000  61000.000000             0.0              0.0            1.0
4  40.000000  63777.777778             0.0              1.0            0.0
5  35.000000  58000.000000             1.0              0.0            0.0
6  38.777778  52000.000000             0.0              0.0            1.0
7  48.000000  79000.000000             1.0              0.0            0.0
8  50.000000  83000.000000             0.0              1.0            0.0
9  37.000000  67000.000000             1.0              0.0            0.0

In [30]:
# Splitting dataset as Training and Testing

from sklearn.model_selection import train_test_split
x_train, x_test, y_train,y_test = train_test_split(x,y,test_size = 0.2, random_state = 1)

In [31]:
x_train

Age        Salary  Country_France  Country_Germany  Country_Spain
6  1.110223e-16 -1.073570e+00             0.0              0.0            1.0
4  1.776089e-01  2.357833e-16             0.0              1.0            0.0
0  7.588744e-01  7.494733e-01             1.0              0.0            0.0
3 -1.130238e-01 -2.532004e-01             0.0              0.0            1.0
1 -1.711504e+00 -1.438178e+00             0.0              0.0            1.0
7  1.340140e+00  1.387538e+00             1.0              0.0            0.0
8  1.630773e+00  1.752147e+00             0.0              1.0            0.0
5 -5.489729e-01 -5.266569e-01             1.0              0.0            0.0

In [32]:
x_test

Age    Salary  Country_France  Country_Germany  Country_Spain
2 -1.275555 -0.891265             0.0              1.0            0.0
9 -0.258340  0.293712             1.0              0.0            0.0

In [33]:
y_train

Purchased
6          0
4          1
0          0
3          0
1          1
7          1
8          0
5          1

In [35]:
y_test

Purchased
2          0
9          1